version: '3.1'
services:
  db:
    image: mysql:8
    container_name: $CODENAME-mysql
    restart: unless-stopped
    user: "${UID}:${GID}"
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
    ports:
      - $MYSQL_PORT:3306
    volumes:
      - ./mysql/my.cnf:/etc/my.cnf
      - ./mysql/data:/var/lib/mysql
      - ./mysql/mysql.log:/var/log/mysql/mysql.log
  backend:
    build:
      context: backend
      dockerfile: backend.Dockerfile
    image: $CODENAME-backend
    container_name: $CODENAME-backend
    user: ${UID}:${UID}
    entrypoint: ["./wait.sh"]
    depends_on:
      - db
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
  frontend:
    build:
      context: frontend
      dockerfile: frontend.Dockerfile
    image: $CODENAME-frontend
    container_name: $CODENAME-frontend
    depends_on:
      - backend
    ports:
      - $HTTP_PORT:8080
    volumes:
      - ./frontend:/frontend
