# Generated by Django 3.2.12 on 2022-05-11 10:33

from django.db import migrations, models
import pkspotapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapsSpots',
            fields=[
                ('mapid', models.IntegerField(db_column='mapId', primary_key=True, serialize=False)),
                ('spotid', models.IntegerField(db_column='spotId')),
            ],
            options={
                'db_table': 'maps_spots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=pkspotapp.models.upload_to, verbose_name='Image')),
                ('spotid', models.IntegerField(db_column='spotId')),
            ],
            options={
                'db_table': 'pics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=24)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'spots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('psw', models.CharField(max_length=50)),
                ('social', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersMaps',
            fields=[
                ('userid', models.IntegerField(db_column='userId', primary_key=True, serialize=False)),
                ('mapid', models.IntegerField(db_column='mapId')),
                ('role', models.CharField(max_length=21)),
            ],
            options={
                'db_table': 'users_maps',
                'managed': False,
            },
        ),
    ]
