# Generated by Django 4.0.3 on 2022-03-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Maps',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name_plural': 'Maps',
                'db_table': 'maps',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MapsSpots',
            fields=[
                ('mapid', models.IntegerField(db_column='mapId', primary_key=True, serialize=False)),
                ('spotid', models.IntegerField(db_column='spotId')),
            ],
            options={
                'verbose_name_plural': 'Maps_Spots',
                'db_table': 'maps_spots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500, unique=True)),
                ('spotid', models.IntegerField(db_column='spotId')),
            ],
            options={
                'verbose_name_plural': 'Pics',
                'db_table': 'pics',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Spots',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.IntegerField()),
                ('type', models.CharField(max_length=24)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Spots',
                'db_table': 'spots',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30, unique=True)),
                ('psw', models.CharField(max_length=41)),
                ('social', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name_plural': 'Users',
                'db_table': 'users',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UsersMaps',
            fields=[
                ('userid', models.IntegerField(db_column='userId', primary_key=True, serialize=False)),
                ('mapid', models.IntegerField(db_column='mapId')),
                ('role', models.CharField(max_length=21)),
            ],
            options={
                'verbose_name_plural': 'Users_Maps',
                'db_table': 'users_maps',
                'managed': False,
            },
        ),
    ]
