# Generated by Django 3.2.12 on 2022-05-18 19:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import pkspotapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Map',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'maps',
            },
        ),
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('social', models.CharField(max_length=150, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'my_user',
            },
        ),
        migrations.CreateModel(
            name='UserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('C', 'Creator'), ('E', 'Editor'), ('V', 'Viewer')], default='V', max_length=1)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkspotapp.map')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkspotapp.myuser')),
            ],
            options={
                'db_table': 'users_maps',
                'unique_together': {('user', 'map')},
            },
        ),
        migrations.CreateModel(
            name='Spot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
                ('name', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('S', 'Spot'), ('P', 'Parkour Park'), ('G', 'Gym'), ('U', 'Undercover Spot')], default='S', max_length=1)),
                ('description', models.TextField(blank=True, null=True)),
                ('adder', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='pkspotapp.myuser')),
            ],
            options={
                'db_table': 'spots',
            },
        ),
        migrations.CreateModel(
            name='Pics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to=pkspotapp.models.upload_to, verbose_name='Image')),
                ('spot_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkspotapp.spot')),
            ],
            options={
                'db_table': 'pics',
            },
        ),
        migrations.AddField(
            model_name='myuser',
            name='maps',
            field=models.ManyToManyField(through='pkspotapp.UserMap', to='pkspotapp.Map'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='map',
            name='spots',
            field=models.ManyToManyField(to='pkspotapp.Spot'),
        ),
    ]
