# Generated by Django 4.0.3 on 2022-03-20 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maps',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='mapsspots',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='pics',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='spots',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usersmaps',
            options={'managed': False},
        ),
    ]
