# Generated by Django 4.1 on 2022-08-27 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myuser',
            name='maps',
            field=models.ManyToManyField(related_name='users', through='pkspotapp.UserMap', to='pkspotapp.map'),
        ),
    ]
