# Generated by Django 3.2.12 on 2022-05-18 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pics',
            new_name='Pic',
        ),
        migrations.RenameField(
            model_name='pic',
            old_name='spot_id',
            new_name='spot',
        ),
    ]
