# Generated by Django 3.2.12 on 2022-05-23 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0002_auto_20220518_2157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='map',
            name='spots',
            field=models.ManyToManyField(null=True, to='pkspotapp.Spot'),
        ),
    ]
