# Generated by Django 4.1 on 2022-08-27 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0002_alter_myuser_maps'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyUserMap',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('C', 'Creator'), ('E', 'Editor'), ('V', 'Viewer')], default='V', max_length=1)),
                ('map', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkspotapp.map')),
            ],
            options={
                'db_table': 'myusers_maps',
            },
        ),
        migrations.AlterField(
            model_name='myuser',
            name='maps',
            field=models.ManyToManyField(related_name='myusers', through='pkspotapp.MyUserMap', to='pkspotapp.map'),
        ),
        migrations.DeleteModel(
            name='UserMap',
        ),
        migrations.AddField(
            model_name='myusermap',
            name='myuser',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pkspotapp.myuser'),
        ),
        migrations.AlterUniqueTogether(
            name='myusermap',
            unique_together={('myuser', 'map')},
        ),
    ]
