# Generated by Django 4.1 on 2022-09-01 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0003_myusermap_alter_myuser_maps_delete_usermap_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='map',
            name='spots',
        ),
        migrations.AddField(
            model_name='map',
            name='spotes',
            field=models.ManyToManyField(blank=True, to='pkspotapp.spot'),
        ),
    ]
