# Generated by Django 4.1 on 2022-09-10 08:38

from django.db import migrations, models
import pkspotapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0004_remove_map_spots_map_spotes'),
    ]

    operations = [
        migrations.RenameField(
            model_name='map',
            old_name='spotes',
            new_name='spots',
        ),
        migrations.AddField(
            model_name='map',
            name='icon',
            field=models.ImageField(blank=True, null=True, upload_to=pkspotapp.models.upload_map_icon, verbose_name='Image'),
        ),
    ]
