# Generated by Django 3.2.12 on 2022-06-01 20:21

from django.db import migrations, models
import pkspotapp.models


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0004_alter_map_spots'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to=pkspotapp.models.upload_profile_picture, verbose_name='Image'),
        ),
    ]
