# Generated by Django 4.1 on 2022-09-20 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pkspotapp', '0005_rename_spotes_map_spots_map_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='map',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
